Repository Ijwu/Archipelago.HollowKnight, pull requests merged in 2022-06, with the labels that each got.

#85 Adds support for generic location costs.
  Archipelago.HollowKnight/ArchipelagoRandomizer.cs
  Archipelago.HollowKnight/SlotData/SlotDataExtract.cs
Labels: bug, enhancement

#81 Deathlink, first pass.
  Archipelago.HollowKnight/Archipelago.HollowKnight.csproj
  Archipelago.HollowKnight/Archipelago.cs
  Archipelago.HollowKnight/DeathLinkSupport.cs
  Archipelago.HollowKnight/Enums.cs
  Archipelago.HollowKnight/Resources/DeathLinkIcon.png
  Archipelago.HollowKnight/ShadeInfo.cs
  Archipelago.HollowKnight/SlotData/SlotOptions.cs
Labels: enhancement, server-side

#103 Improve automatic hinting of scouted locations.
  Archipelago.HollowKnight/Archipelago.cs
  Archipelago.HollowKnight/IC/ArchipelagoTags.cs
  Archipelago.HollowKnight/IC/PlacementUtils.cs
Labels: enhancement

#100 Contains small adjustments to make CostSanity and other shop stuff work.
  Archipelago.HollowKnight/ArchipelagoRandomizer.cs
Labels: enhancement

#105 Contains assorted placement bugfixes.
  Archipelago.HollowKnight/ArchipelagoRandomizer.cs
Labels: bug

#91 Move user paths outside csproj
  .gitignore
  Archipelago.HollowKnight.sln
  Archipelago.HollowKnight/Archipelago.HollowKnight.csproj
  Directory.Build.props.todo
  README.md
Labels: documentation
